set -o vi

if [ -x $(command -v brew) ]; then
  DIR_PREFIX=$(brew --prefix)
else
  DIR_PREFIX=""
fi

if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

function prompt_command() {
  export PS1='$(__git_ps1) \w [\u]\$ '
}

export PROMPT_COMMAND=prompt_command

if [ -f $DIR_PREFIX/etc/bash_completion ]; then
  source $DIR_PREFIX/etc/bash_completion
fi

export LC_ALL=en_US.UTF-8

if [ -d $HOME/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d $HOME/.local/bin ]; then
  export PATH=$PATH:$HOME/.local/bin
fi

if [ -d $HOME/Library/Python/3.7/bin ]; then
    export PATH=$PATH:$HOME/Library/Python/3.7/bin
fi

if [ -d /usr/local/opt/postgresql@10/bin ]; then
  export PATH=$PATH:/usr/local/opt/postgresql@10/bin
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if command -v rg >/dev/null && command -v fzf >/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
fi

if [ -f ~/.ghcup/env ]; then
  source ~/.ghcup/env
fi

# Aliases
if command -v nvim >/dev/null; then
  alias vim=nvim
fi

alias dcps="docker-compose ps"

function dps() {
  if command -v docker-pretty-ps>/dev/null; then
    cmd="docker-pretty-ps"
  else
    cmd="docker ps"
  fi

  eval "$cmd"
}

function mcd() {
  mkdir $1 && cd $1;
}
