# vi: ft=sh

export CLICOLOR=1
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"

if [ -r ~/.bashrc ]; then
  . ~/.bashrc
fi

export PATH="/usr/local/opt/binutils/bin:$PATH"
