---

- hosts: localhost
  vars:
    pip_packages:
      - docker-pretty-ps

    brew_packages: 
      - ctags
      - diff-so-fancy
      - ripgrep
      - fzf
      - reattach-to-user-namespace

  tasks:
    - name: Symlink gitconfig
      file:
        src: "{{ playbook_dir }}/files/gitconfig"
        dest: "~/.gitconfig"
        state: link
        force: yes
      tags:
        - git

    - name: Symlink vimrc
      file:
        src: "{{ playbook_dir }}/files/vimrc"
        path: "~/.vimrc"
        state: link
        force: yes
      tags:
        - vim

    - name: Symlink vint config
      file:
        src: "{{ playbook_dir }}/files/vintrc.yml"
        dest: "~/.vintrc.yml"
        state: link
        force: yes
      tags:
        - vim

    - name: Create symlink for neovim
      shell: '[ -d ~/.config/nvim ] && ln -sf "{{ playbook_dir }}/files/vimrc" ~/.config/nvim/init.vim'
      tags:
        - vim

    - name: Create python3 virtualenv for neovim
      pip:
        virtualenv: ~/.config/pynvim3
        virtualenv_python: python3.7
        virtualenv_command: venv
        requirements: "{{ playbook_dir }}/files/python3-requirements.txt"
        state: forcereinstall
        # extra_args: --user
      tags:
        - vim

    - name: Symlink pycodestyle
      file:
        src: "{{ playbook_dir }}/files/pycodestyle"
        dest: ~/.config/pycodestyle
        state: link
        force: yes
      tags:
        - vim

    - name: Symlink pylintrc
      file:
        src: "{{ playbook_dir }}/files/pylintrc"
        dest: ~/.pylintrc
        state: link
        force: yes
      tags:
        - vim

    - name: Symlink tmux config
      file:
        src: "{{ playbook_dir }}/files/tmux.conf"
        dest: ~/.tmux.conf
        state: link
        force: yes
      tags:
        - tmux

    - name: Symlink bash_profile
      file:
        src: "{{ playbook_dir }}/files/bash_profile"
        dest: ~/.bash_profile
        state: link
        force: yes
      tags:
        - bash

    - name: Symlink bashrc
      file:
        src: "{{ playbook_dir }}/files/bashrc"
        dest: ~/.bashrc
        state: link
        force: yes
      tags:
        - bash

    - name: Install homebrew packages (MacOS only)
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      tags:
        - homebrew
        - macos
        - deps

    - name: Install python packages
      pip:
        name: "{{ pip_packages }}"
        state: present
      tags:
        - deps

